// The interface text of the theme. site.language in config.yaml picks the set:
// a language that starts with "zh" reads Chinese, every other reads English.
const strings = {
  "en": {
    "skip_to_content": "Skip to main content",
    "home": "Home",
    "menu": "Menu",
    "toggle_menu": "Toggle menu",
    "search": "Search",
    "search_placeholder": "Search…",
    "search_label": "Search articles and ideas",
    "search_scope": "Titles, summaries and tags · Published content only",
    "search_close": "Close search",
    "search_retry": "Retry",
    "search_results": "Search results",
    "search_select_hint": "↑ ↓ or Tab to select",
    "search_close_hint": "Esc to close",
    "browse_blog": "Browse Blog",
    "browse_tags": "Browse Tags",
    "search_loading": "Loading search…",
    "search_failed": "Could not load search. Retry or browse the archives.",
    "search_empty": "No published content to search yet.",
    "search_no_results": "No results. Try a title or a topic.",
    "search_browse": "Browse recent writing and ideas.",
    "search_count_one": "1 result.",
    "search_count": "{count} results.",
    "search_truncated": "{count} results · Showing the first 20; refine your search.",
    "copy_code": "Copy code",
    "copied": "Copied",
    "copy_failed": "Select the code to copy manually",
    "dark_mode": "Dark mode",
    "site_index": "Site index",
    "main_navigation": "Main navigation",
    "rail_note": "Writing & ideas.",
    "footer_thanks": "Thanks for reading.",
    "footer_links": "Footer links",
    "powered_by": "Content by escaping",
    "featured": "Featured",
    "recent_articles": "Recent Articles",
    "all_articles": "All articles",
    "no_writing_yet": "No published writing yet.",
    "home_intro": "I share what I learn on {blog}. You can read a little more {about}.",
    "home_intro_blog": "my blog",
    "home_intro_about": "about me",
    "blog": "Blog",
    "blog_eyebrow": "Notes in long form",
    "blog_caption": "A collection, in chronological order.",
    "explore_by_topic": "Explore by topic",
    "blog_pagination": "Blog pagination",
    "newer": "← Newer",
    "older": "Older →",
    "empty_writing": "No writing yet. Check back soon.",
    "ideas": "Ideas",
    "ideas_eyebrow": "Room for a thought",
    "ideas_caption": "Not everything needs to be an essay.",
    "ideas_empty_title": "A little room to think.",
    "ideas_empty_body": "No published ideas yet. There is more to explore in the writing archive.",
    "explore_writing": "Explore the writing",
    "about": "About",
    "back_home": "Back to Home",
    "back_to_section": "Back to {section}",
    "back_to_top": "Back to top",
    "tags": "Tags",
    "tags_eyebrow": "Follow a thread",
    "tags_caption": "One topic, different moments in time.",
    "tags_empty": "No topics yet.",
    "tags_label": "Tags",
    "related_articles": "{count} related articles",
    "discuss": "Discuss",
    "article_navigation": "Article navigation",
    "previous": "Previous",
    "next": "Next",
    "on_this_page": "On this page",
    "conversation": "Conversation",
    "comments_intro": "Have something to add? Join the conversation on this Issue.",
    "comments_loading": "Loading comments…",
    "comments_noscript": "Comments require JavaScript. You can also read and reply on GitHub.",
    "comments_unavailable": "Comments may not be available. Your network or browser privacy settings may block third-party content.",
    "comments_view_on_github": "View or add comment on GitHub →",
    "not_found": "Page not found",
    "not_found_body": "This page does not exist, or it has moved.",
    "about_empty": "Nothing here yet."
  },
  "zh": {
    "skip_to_content": "跳到正文",
    "home": "首页",
    "menu": "菜单",
    "toggle_menu": "展开或收起菜单",
    "search": "搜索",
    "search_placeholder": "搜索…",
    "search_label": "搜索文章和想法",
    "search_scope": "标题、摘要和标签 · 仅已发布内容",
    "search_close": "关闭搜索",
    "search_retry": "重试",
    "search_results": "搜索结果",
    "search_select_hint": "↑ ↓ 或 Tab 选择",
    "search_close_hint": "Esc 关闭",
    "browse_blog": "浏览博客",
    "browse_tags": "浏览标签",
    "search_loading": "正在加载搜索…",
    "search_failed": "无法加载搜索。请重试，或直接浏览归档。",
    "search_empty": "还没有可搜索的已发布内容。",
    "search_no_results": "没有结果。试试标题或主题。",
    "search_browse": "浏览最近的文章和想法。",
    "search_count_one": "1 个结果。",
    "search_count": "{count} 个结果。",
    "search_truncated": "{count} 个结果 · 只显示前 20 个，请缩小范围。",
    "copy_code": "复制代码",
    "copied": "已复制",
    "copy_failed": "请手动选中代码复制",
    "dark_mode": "深色模式",
    "site_index": "站点目录",
    "main_navigation": "主导航",
    "rail_note": "写作与想法。",
    "footer_thanks": "感谢阅读。",
    "footer_links": "页脚链接",
    "powered_by": "内容由 escaping 导出",
    "featured": "精选",
    "recent_articles": "最近文章",
    "all_articles": "全部文章",
    "no_writing_yet": "还没有发布的文章。",
    "home_intro": "我在{blog}分享学到的东西。想多了解我，可以看看{about}。",
    "home_intro_blog": "博客",
    "home_intro_about": "关于我",
    "blog": "博客",
    "blog_eyebrow": "长一点的笔记",
    "blog_caption": "按时间排列的全部文章。",
    "explore_by_topic": "按主题浏览",
    "blog_pagination": "博客分页",
    "newer": "← 较新",
    "older": "较早 →",
    "empty_writing": "还没有文章，过段时间再来看看。",
    "ideas": "想法",
    "ideas_eyebrow": "留给一个念头",
    "ideas_caption": "不是每个想法都要写成文章。",
    "ideas_empty_title": "这里还很安静。",
    "ideas_empty_body": "还没有发布的想法，可以先看看文章。",
    "explore_writing": "去看看文章",
    "about": "关于",
    "back_home": "返回首页",
    "back_to_section": "返回{section}",
    "back_to_top": "回到顶部",
    "tags": "标签",
    "tags_eyebrow": "顺着一个主题读下去",
    "tags_caption": "同一个主题，不同的时间。",
    "tags_empty": "还没有标签。",
    "tags_label": "标签",
    "related_articles": "{count} 篇相关文章",
    "discuss": "讨论",
    "article_navigation": "文章导航",
    "previous": "上一篇",
    "next": "下一篇",
    "on_this_page": "本页目录",
    "conversation": "讨论",
    "comments_intro": "有想法？欢迎在这个 Issue 下留言。",
    "comments_loading": "正在加载评论…",
    "comments_noscript": "评论需要 JavaScript。你也可以在 GitHub 上阅读和回复。",
    "comments_unavailable": "评论可能无法加载：网络或浏览器隐私设置可能拦截了第三方内容。",
    "comments_view_on_github": "在 GitHub 上查看或评论 →",
    "not_found": "页面不存在",
    "not_found_body": "这个页面不存在，或者已经移走了。",
    "about_empty": "这里还没有内容。"
  }
} as const;

export type Strings = Record<keyof (typeof strings)["en"], string>;

export function stringsFor(language: string): Strings & { language: string } {
  const key = language.toLowerCase().startsWith("zh") ? "zh" : "en";
  return { ...strings[key], language: key };
}
